# Generated by Django 4.1.5 on 2023-06-01 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=200)),
                ('experiencia_profissional', models.TextField()),
                ('educacao', models.TextField()),
                ('habilidades', models.TextField()),
                ('data_criacao', models.DateField()),
                ('portfolio', models.URLField()),
                ('redes_sociais', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateField()),
                ('website', models.URLField()),
                ('ramo_atuacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('requisitos', models.TextField()),
                ('data_publicacao', models.DateField()),
                ('data_encerramento', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tipo_contrato', models.CharField(max_length=100)),
                ('local_trabalho', models.CharField(max_length=200)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='Seleção.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_candidatura', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seleção.candidato')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seleção.vaga')),
            ],
        ),
    ]
