# Generated by Django 4.1.5 on 2023-06-01 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seleção', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='redes_sociais',
        ),
        migrations.AddField(
            model_name='candidato',
            name='vaga_interesse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='Seleção.vaga'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='habilidades',
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('conhecimentos', models.ManyToManyField(to='Seleção.conhecimento')),
            ],
        ),
        migrations.AddField(
            model_name='candidato',
            name='habilidades',
            field=models.ManyToManyField(to='Seleção.habilidade'),
        ),
    ]
