# Generated by Django 4.1.5 on 2023-06-01 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seleção', '0002_conhecimento_remove_candidato_data_criacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habilidade',
            name='conhecimentos',
        ),
        migrations.DeleteModel(
            name='Conhecimento',
        ),
    ]
