# Generated by Django 4.1.5 on 2023-06-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seleção', '0003_remove_habilidade_conhecimentos_delete_conhecimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='candidatos/arquivos'),
        ),
    ]
