# Generated by Django 4.1.5 on 2023-06-01 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seleção', '0004_candidato_arquivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidato',
            old_name='arquivo',
            new_name='curriculo',
        ),
    ]
