# Generated by Django 4.1.5 on 2023-06-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seleção', '0005_rename_arquivo_candidato_curriculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='curriculo',
            field=models.FileField(blank=True, null=True, upload_to='candidatos/curriculos/'),
        ),
    ]
